/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package votingapp;


import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author adamm
 */
public class CheckVoteWithHashGUI extends javax.swing.JFrame {

    private VotingGUI vGUI;

    /**
     * Creates new form TotalVotesGUI
     */
    public CheckVoteWithHashGUI() {
        initComponents();
    }

    public void setVotingGUI(VotingGUI vGUI) {
        this.vGUI = vGUI;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterHashTextField = new javax.swing.JTextField();
        checkVoteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Enter your hash");

        checkVoteButton.setText("Check");
        checkVoteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkVoteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enterHashTextField)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(checkVoteButton)
                .addContainerGap(223, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(enterHashTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checkVoteButton)
                .addGap(12, 12, 12))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void checkVoteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkVoteButtonActionPerformed
        // method to check the hash that is entered when the check button is clicked
        
        // checking the entered hash and removing whitespace using trim()
        String enteredHash = enterHashTextField.getText().trim();

        if (enteredHash.isEmpty()) { // if the hash text field is empty, display a message
            JOptionPane.showMessageDialog(this, "Enter a valid hash");
            return;
        }

        HashMap<String, byte[]> voteHashes = vGUI.getVoteHashes(); // getting the hashmap containing the candidate name and hash from VotingGUI

        for (Map.Entry<String, byte[]> entry : voteHashes.entrySet()) { // iterate throuugh the hashmap and retrieve the hashes and candidate names
            // get the key and value from the hash map
            String candidateName = entry.getKey();
            byte[] voteHash = entry.getValue();

            String calculatedHash = vGUI.calculateHash(voteHash); // using the calculateHash method in VotingGUI to calculate the hash

            if (enteredHash.equals(calculatedHash)) { // if the entered hash is valid
                JOptionPane.showMessageDialog(this, "You voted for " + candidateName); // display the corresponding key (candidate name)
                return;
            }
        }
        JOptionPane.showMessageDialog(this, "No candidate found for that hash"); // if there is no match for the hash in the hashmap, return a message
    }//GEN-LAST:event_checkVoteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckVoteWithHashGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckVoteWithHashGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckVoteWithHashGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckVoteWithHashGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckVoteWithHashGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkVoteButton;
    private javax.swing.JTextField enterHashTextField;
    // End of variables declaration//GEN-END:variables
}
